---
sudo: required
cache:
  node: true
  directories:
    - vendor/bundle
    - node_modules
    - $HOME/.nvm
addons:
  postgresql: 10
  chrome: stable
before_script:
  # Repo for Yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - yarn
  - bundle exec rails db:create RAILS_ENV=test
language: ruby
rvm:
  - 2.6.5
script:
  - bundle exec rake assets:precompile RAILS_ENV=test
  - bundle exec rails db:test:load RAILS_ENV=test
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec
services:
  - redis-server
before_install: gem install bundler -v 2.0.1
